import messages from './messages'

export const cardItems = [
  {
    id: 'foieGras',
    topTitle: messages.cardTopTitle,
    rejection: messages.rejection,
    question: messages.cardQuestion,
    byu: messages.cardBuy,
    title: messages.cardTitle,
    taste: messages.tasteFoieGras,
    portionNumber: messages.portionNumberFoieGras,
    portion: messages.portion,
    mouseNumber: messages.mouseNumberFoieGras,
    mouse: messages.mouseFoieGras,
    weight: messages.cardWeight,
    weightDescription: messages.cardWeightDescription,
    selected: messages.cardSelectedFoieGras,
    disabled: messages.cardDisabledFoieGras,
    isDisabled: false,
  },
  {
    id: 'fish',
    topTitle: messages.cardTopTitle,
    title: messages.cardTitle,
    taste: messages.tasteFish,
    portionNumber: messages.portionNumberFish,
    portion: messages.portion,
    mouseNumber: messages.mouseNumberFish,
    mouse: messages.mouseFish,
    weight: messages.cardWeight,
    weightDescription: messages.cardWeightDescription,
    rejection: messages.rejection,
    question: messages.cardQuestion,
    byu: messages.cardBuy,
    selected: messages.cardSelectedFish,
    disabled: messages.cardDisabledFish,
    isDisabled: false,
  },
  {
    id: 'chicken',
    topTitle: messages.cardTopTitle,
    title: messages.cardTitle,
    taste: messages.tasteChicken,
    portionNumber: messages.portionNumberChicken,
    portion: messages.portion,
    mouseNumber: messages.mouseNumberChicken,
    mouse: messages.mouseChicken,
    weight: messages.cardWeight,
    weightDescription: messages.cardWeightDescription,
    rejection: messages.rejection,
    question: messages.cardQuestion,
    byu: messages.cardBuy,
    selected: messages.cardSelectedChicken,
    disabled: messages.cardDisabledChicken,
    isDisabled: true,
  },
]
